parameters:
    zurb_ink.inlinecss.class: Stafox\ZurbInkBundle\Service\InlineCss
    zurb_ink.inlinecss.twig.class: Stafox\ZurbInkBundle\Twig\InlineCssExtension
    zurb_ink.inky.twig.class: Stafox\ZurbInkBundle\Twig\InkyExtension
    zurb_ink.inky.class: Hampe\Inky\Inky
    zurb_ink.inky.gridColumns: 12
    zurb_ink.inky.componentFactories: []
    zurb_ink.csstoinlinestyles.class: voku\CssToInlineStyles\CssToInlineStyles

services:
    zurb_ink.csstoinlinestyles:
        class: "zurb_ink.csstoinlinestyles.class"

    zurb_ink.inlinecss:
        class: "%zurb_ink.inlinecss.class%"
        arguments: ["@zurb_ink.csstoinlinestyles"]

    zurb_ink.inlinecss.twig:
        class: "%zurb_ink.inlinecss.twig.class%"
        arguments: ["@zurb_ink.inlinecss", "@file_locator"]
        tags:
            - { name: twig.extension }

    zurb_ink.inky:
        class:  "%zurb_ink.inky.class%"
        arguments: ["%zurb_ink.inky.gridColumns%", "%zurb_ink.inky.componentFactories%"]

    zurb_ink.inky.twig:
        class:  "%zurb_ink.inky.twig.class%"
        arguments: ["@zurb_ink.inky"]
        tags:
            - { name: twig.extension }